# mkdocs.yml
# For the specification, see <https://www.mkdocs.org/user-guide/configuration/>.

# Project information

# Set the copyright information to be included in the documentation by the
# theme.
copyright: © 2025 プレハブ小屋 All rights reserved.

# The path from the base repo_url to the docs directory when directly viewing a
# page, accounting for specifics of the repository host (e.g. GitHub, Bitbucket,
# etc), the branch, and the docs directory itself. MkDocs concatenates
# `repo_url` and `edit_uri`, and appends the input path of the page.
edit_uri: edit/main/docs/

# Set the remote branch to commit to when using gh-deploy to deploy to GitHub
# Pages.
#
# default: gh-pages
#remote_branch: gh-pages

# Set the remote name to push to when using gh-deploy to deploy to GitHub Pages.
#
# default: origin
#remote_name: origin

# link to your repository (GitHub, Bitbucket, GitLab, ...) on each page.
repo_url: https://github.com/showa-yojyo/taoup/

# This will add a meta tag to the generated HTML header.
site_author: プレハブ小屋

# This will add a meta tag to the generated HTML header.
site_description: 読書ノートの一部

# the main title for the project documentation
site_name: The Art of Unix Programming 読書ノート

# the canonical URL of the site
site_url: https://github.com/showa-yojyo/taoup/

# Documentation layout
#draft_focs: []
#exclude_docs: []
nav:
  - Home: index.md
  - Notes:
    - Preface: preface.md
    - Context:
      - Philosophy: context/philosophy.md
      - History: context/history.md
      - Contrasts: context/contrasts.md
    - Design:
      - Modularity: design/modularity.md
      - Textuality: design/textuality.md
      - Transparency: design/transparency.md
      - Multiprogramming: design/multiprogram.md
      - Minilanguages: design/minilanguages.md
      - Generation: design/generation.md
      - Configuration: design/configuration.md
      - Interfaces: design/interface.md
      - Optimization: design/optimization.md
      - Complexity: design/complexity.md
    - Implementation:
      - Languages: implementation/languages.md
      - Tools: implementation/tools.md
      - Reuse: implementation/reuse.md
    - Community:
      - Portability: community/portability.md
      - Documentation: community/documentation.md
      - Open Source: community/opensource.md
      - Futures: community/futures.md
  - Issues: https://github.com/showa-yojyo/taoup/issues
#not_in_nav:
validation:
  absolute_links: relative_to_docs
  anchors: warn
  omitted_files: warn
  unrecognized_links: warn

# Build directories
#docs_dir: docs
#extra: {}
extra_css:
  - css/style.css
#extra_javascript:
#  - path: js/load-mathjax.js
#    async: true
#extra_templates: []
#site_dir: site

theme:
  color_mode: auto
#  highlightjs: on
#  hljs_style: github
#  hljs_style_dark: github-dark
  locale: ja
  name: mkdocs
  nav_style: primary
  navigation_depth: 3
  shortcuts:
    help: 191
    next: 78
    previous: 80
    search: 83
  user_color_mode_toggle: on

# Preview controls
#dev_addr: "127.0.0.1:8000"
strict: true

# about/license.md => /about/license.html
use_directory_urls: false

# Formatting options

markdown_extensions:
  - admonition
  - def_list
  - sane_lists
  - toc:
      permalink: true
      title: 見出し一覧
      toc_depth: "2-6"
hooks:
  - hooks.py
plugins:
  - search:
      enabled: True
      indexing: sections
      lang:
        - en
      min_search_length: 4
      prebuild_index: False
